apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
spec:
  selector:
    matchLabels:
      app: simple-go-app
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-go-app
    spec:
      containers:
      - name: go-app-container
        image: papp012/goapp
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3002